spring.datasource.url=jdbc:postgresql://localhost:5432/tictactoe
spring.datasource.username=tictactoe
spring.datasource.password=tictactoe
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
server.port=8081